In [1]:
import sklearn.datasets as skd

In [2]:
c=['alt.atheism','soc.religion.christian','comp.graphics','sci.med']
news_train=skd.load_files("E:/mousita/ML/datasets/newgroup/20news-bydate-train",categories=c,encoding="ISO-8859-1")
news_test=skd.load_files("E:/mousita/ML/datasets/newgroup/20news-bydate-test",categories=c,encoding="ISO-8859-1")

In [7]:
news_train.target[4]

0

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [9]:
text_clf=Pipeline([('vect',TfidfVectorizer()),
                  ('clf',MultinomialNB())])

In [10]:
#train model
text_clf.fit(news_train.data,news_train.target)

Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [11]:
predicted=text_clf.predict(news_test.data)

In [12]:
from sklearn.metrics import accuracy_score

In [13]:
accuracy_score(news_test.target,predicted)

0.8348868175765646

In [11]:
news_test.target

array([3, 0, 3, ..., 3, 1, 1])

In [8]:
text_clf.predict(["In article rind@enterprise.bih.harvard.edu (David Rind) writes:"])

array([2])

In [11]:
predicted

array([3, 0, 3, ..., 3, 1, 1])

In [12]:
news_test.target

array([3, 0, 3, ..., 3, 1, 1])